---
# tasks file for roles
    - name: Creates directory gitlab
      file:
        path: 
          - /config-gl
          - /logs-gl
          - /data-gl
        state: directory

    - name: Pull image gitlab-ce
      docker_image:
        name: gitlab/gitlab-ce:latest
        source: pull

    - name: command install gitlab
      command: bash -c "sudo docker run --detach --publish 8011:443 --publish 8012:80 --publish 8013:22 --name gitlab-sv --volume /config-gl/config:/etc/gitlab --volume /logs-gl/logs:/var/log/gitlab --volume /data-gl/data:/var/opt/gitlab gitlab/gitlab-ce:latest"
    
    - name: sleep wait
      command: /bin/sleep 40

    - name: cat pass gitlab
      command: bash -c "sudo docker exec -it gitlab-sv grep 'Password:' /etc/gitlab/initial_root_password"
      register: pass_git
 
    - debug:
        var: pass_git.stdout_lines