---
# tasks file for roles
    - name: Creates directory
      file:
        path: ./datajenkins
        state: directory

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: command install jenkins
      command: bash -c "sudo docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):$(which docker) -v `pwd`/datajenkins:/var/jenkins_home  -p 8080:8080  --user 0:0 --name jenkins-server -d jenkins/jenkins:lts"
    
    - name: sleep wait
      command: /bin/sleep 60

    - name: cat pass jenkins
      command: bash -c "sudo docker exec jenkins-server cat /var/jenkins_home/secrets/initialAdminPassword" 
      register: pass_jen
    
    - debug:
        var: pass_jen.stdout_lines